---
name: 'Custom GitHub Action'
description: 'A GitHub Action that takes an input and returns the square of the number'
inputs:
  operation:
    description: 'Operation to be performed, can be a deploy or delete'
    required: true
    type: choice
    options:
      - deploy
      - delete
  stackset_name:
    description: 'Name of StackSet on which operation is being performed'
    required: true
  stackset_description:
    description: 'Description of StackSet'
    required: false
  template_path:
    description: 'Template path'
    required: true
  org_ou_ids:
    description: 'Comma-separated list of AWS Org OU ids'
    required: true
  account_ids:
    description: 'Comma-separated list of AWS Account ids to limit the operations to; currently only supported for "deploy" operation'
    required: false
  regions:
    description: 'Comma-separated list of regions to deploy to'
    required: false
    default: 'ap-southeast-2'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
        - ${{ inputs.operation }}
        - ${{ inputs.stackset_name }}
        - ${{ inputs.stackset_description }}
        - ${{ inputs.template_path }}
        - ${{ inputs.org_ou_ids }}
        - ${{ inputs.account_ids }}
        - ${{ inputs.region }}
