[tool.poetry]
name = "stack-set-helper-action"
version = "0.1.0"
description = ""
authors = ["Leo Alves <leo@adatree.com.au>"]
readme = "README.md"
packages = [{include = "stack_set_helper_action"}]

[tool.poetry.dependencies]
python = "3.8.15"
boto3 = "^1.24.46"
click = "^8.1.3"


[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
pylint = "^2.14.5"
pytest = "^7.1.2"

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
