[tool.poetry]
name = "stack-set-helper-action"
version = "0.1.0"
description = ""
authors = ["Leo Alves <leo@adatree.com.au>"]
readme = "README.md"
packages = [{include = "stack_set_helper_action"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

